language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - lib32stdc++6 # For CMake
    - os: osx
      sudo: false
      osx_image: xcode7.3
    - os: linux
      sudo: required
      dist: trusty
      env: EMULATE_AARCH64=1
      services: docker

install: ./.travis/deps.sh
script: ./.travis/build.sh
